# -*- coding: utf-8 -*-
"""
Модуль для локализации интерфейса (RU/EN).
"""

TRANSLATIONS = {
    "ru": {
        "app_title": "Anki German Helper",
        "settings": "Настройки",
        "help": "Справка",
        "open_settings": "Открыть настройки",
        "play_audio": "Воспроизвести аудио",
        "audio_enabled": "Озвучка",
        "audio_enabled_tooltip": "Создавать озвучку при добавлении в Anki",
        "sound_source_original": "Ориг",
        "sound_source_translation": "Перевод",
        "sound_source_tooltip": "Выберите источник текста для озвучки",
        "placeholder_german": "Немецкий текст...",
        "placeholder_translation": "Перевод...",
        "placeholder_context": "Контекст/объяснения...",
        "generate": "Генерировать",
        "cancel_generation": "Отмена генерации",
        "auto_generate": "Авто",
        "auto_generate_tooltip": "Автоматически генерировать перевод при копировании текста",
        "clipboard_monitoring": "Перехват буфера",
        "clipboard_monitoring_tooltip": "Включить/выключить отслеживание буфера обмена",
        "context_enabled": "Контекст",
        "context_enabled_tooltip": "Включить генерацию контекста/объяснений",
        "deck_selection": "Выберите колоду",
        "deck_selection_tooltip": "Выберите колоду Anki для добавления карточек",
        "refresh_decks": "Обновить",
        "create_deck": "Создать колоду",
        "add_to_anki": "В Anki",
        "auto_add": "Авто",
        "auto_add_tooltip": "Автоматически добавлять в Anki после генерации",
        "cancel": "Отмена",
        "ok": "ОК",
        "yes": "Да",
        "no": "Нет",
        "error": "Ошибка",
        "warning": "Предупреждение",
        "success": "Успех",
        "loading": "Загрузка...",
        "anki_not_available": "AnkiConnect недоступен",
        "decks_not_found": "Колоды не найдены",
        "new_deck_name": "Название новой колоды:",
        "deck_created": "Колода '{name}' создана и выбрана.",
        "prompt_saved": "Пресет '{name}' сохранен.",
        "prompt_created": "Пресет '{name}' создан.",
        "delete_prompt_confirm": "Удалить '{name}'?",
        "tab_audio": "Озвучка",
        "tab_prompts": "Промпты",
        "tab_ai": "AI",
        "tab_font": "Шрифт",
        "tab_theme": "Тема",
        "speed_label": "Скорость озвучки:",
        "lang_label": "Язык (lang):",
        "tld_label": "Домена (tld):",
        "test_audio": "Тест озвучки",
        "ai_provider_settings": "Настройки AI провайдера",
        "provider_label": "Провайдер:",
        "ollama_local": "Ollama (локальный AI)",
        "openrouter_cloud": "OpenRouter (облачный AI)",
        "google_gemini": "Google AI (Gemini)",
        "server_url": "URL сервера:",
        "model_label": "Модель:",
        "openrouter_presets": "Пресеты:",
        "api_key_label": "API Ключ:",
        "check_connection": "Проверить подключение",
        "connection_success": "Успешно",
        "connection_failed": "Ошибка подключения",
        "font_family_label": "Семейство шрифта:",
        "font_size_label": "Размер шрифта:",
        "preview_text_label": "Пример текста:",
        "appearance_mode": "Режим отображения:",
        "color_theme": "Цветовая тема:",
        "language_label": "Язык интерфейса:",
        "appearance_dark": "Темная",
        "appearance_light": "Светлая",
        "appearance_system": "Системная",
        "theme_blue": "Синяя",
        "theme_green": "Зеленая",
        "theme_dark_blue": "Темно-синяя",
        "rename": "переименовать",
        "save": "Сохранить",
        "new_prompt": "Новый промт",
        "delete": "Удалить",
        "empty_field_warning": "Введите текст для озвучки.",
        "ai_not_configured": "AI не настроен",
        "stop_btn": "Отмена генерации",
        "pin_tooltip": "Закрепить поверх окон",
        "help_tooltip": "Открыть справку (Блокнот)",
        "ai_settings_btn_tooltip": "Нажмите для настройки AI",
        "clipboard_indicator": "👁️Буфер",
        "prompt_label": "Промпт: {name}",
        "translate_prompt_label": "Промпт перевода:",
        "context_prompt_label": "Промпт контекста:",
        "preset_label": "Пресет:",
        "current_model_label": "Текущая модель (используется для генерации):",
        "coming_soon": "Скоро будет доступно",
        "no_presets": "(Нет пресетов)",
        "load_models_error": "Ошибка загрузки моделей:",
        "no_api_key": "Нет ключа",
        "enter_api_key_warning": "Введите API ключ",
        "select_or_enter_manually": "💡 Выберите из списка или введите вручную. Нажмите ★ чтобы сохранить в пресеты.",
    },
    "en": {
        "app_title": "Anki German Helper",
        "settings": "Settings",
        "help": "Help",
        "open_settings": "Open Settings",
        "play_audio": "Play Audio",
        "audio_enabled": "TTS",
        "audio_enabled_tooltip": "Create audio when adding to Anki",
        "sound_source_original": "Orig",
        "sound_source_translation": "Trans",
        "sound_source_tooltip": "Select source text for TTS",
        "placeholder_german": "German text...",
        "placeholder_translation": "Translation...",
        "placeholder_context": "Context/explanations...",
        "generate": "Generate",
        "cancel_generation": "Stop Generation",
        "auto_generate": "Auto",
        "auto_generate_tooltip": "Automatically generate translation on copy",
        "clipboard_monitoring": "Monitor",
        "clipboard_monitoring_tooltip": "Enable/disable clipboard monitoring",
        "context_enabled": "Context",
        "context_enabled_tooltip": "Enable context/explanation generation",
        "deck_selection": "Select Deck",
        "deck_selection_tooltip": "Select Anki deck for cards",
        "refresh_decks": "Refresh",
        "create_deck": "Create Deck",
        "add_to_anki": "To Anki",
        "auto_add": "Auto",
        "auto_add_tooltip": "Automatically add to Anki after generation",
        "cancel": "Cancel",
        "ok": "OK",
        "yes": "Yes",
        "no": "No",
        "error": "Error",
        "warning": "Warning",
        "success": "Success",
        "loading": "Loading...",
        "anki_not_available": "AnkiConnect unavailable",
        "decks_not_found": "Decks not found",
        "new_deck_name": "New deck name:",
        "deck_created": "Deck '{name}' created and selected.",
        "prompt_saved": "Preset '{name}' saved.",
        "prompt_created": "Preset '{name}' created.",
        "delete_prompt_confirm": "Delete '{name}'?",
        "tab_audio": "Audio",
        "tab_prompts": "Prompts",
        "tab_ai": "AI",
        "tab_font": "Font",
        "tab_theme": "Theme",
        "speed_label": "Speech Speed:",
        "lang_label": "Language (lang):",
        "tld_label": "TLD (domain):",
        "test_audio": "Test Audio",
        "ai_provider_settings": "AI Provider Settings",
        "provider_label": "Provider:",
        "ollama_local": "Ollama (local AI)",
        "openrouter_cloud": "OpenRouter (cloud AI)",
        "google_gemini": "Google AI (Gemini)",
        "server_url": "Server URL:",
        "model_label": "Model:",
        "openrouter_presets": "Presets:",
        "api_key_label": "API Key:",
        "check_connection": "Check Connection",
        "connection_success": "Success",
        "connection_failed": "Connection Failed",
        "font_family_label": "Font Family:",
        "font_size_label": "Font Size:",
        "preview_text_label": "Preview Text:",
        "appearance_mode": "Appearance Mode:",
        "color_theme": "Color Theme:",
        "language_label": "UI Language:",
        "appearance_dark": "Dark",
        "appearance_light": "Light",
        "appearance_system": "System",
        "theme_blue": "Blue",
        "theme_green": "Green",
        "theme_dark_blue": "Dark Blue",
        "rename": "rename",
        "save": "Save",
        "new_prompt": "New Prompt",
        "delete": "Delete",
        "empty_field_warning": "Enter text for audio.",
        "ai_not_configured": "AI not configured",
        "stop_btn": "Stop generation",
        "pin_tooltip": "Pin stay on top",
        "help_tooltip": "Open help folder (Notepad)",
        "ai_settings_btn_tooltip": "Click to configure AI",
        "clipboard_indicator": "👁️Clipboard",
        "prompt_label": "Prompt: {name}",
        "translate_prompt_label": "Translation Prompt:",
        "context_prompt_label": "Context Prompt:",
        "preset_label": "Preset:",
        "current_model_label": "Current model (used for generation):",
        "coming_soon": "Coming soon",
        "no_presets": "(No presets)",
        "load_models_error": "Error loading models:",
        "no_api_key": "No key",
        "enter_api_key_warning": "Enter API key",
        "select_or_enter_manually": "💡 Select from list or enter manually. Click ★ to save to presets.",
    }
}

class LocalizationManager:
    def __init__(self):
        self._language = "ru"

    @property
    def language(self):
        return self._language

    @language.setter
    def language(self, value):
        if value in TRANSLATIONS:
            self._language = value

    def get_text(self, key, **kwargs):
        text = TRANSLATIONS.get(self._language, TRANSLATIONS["ru"]).get(key, key)
        if kwargs:
            try:
                return text.format(**kwargs)
            except Exception:
                pass
        return text

localization_manager = LocalizationManager()
